{% set name = "databroker-browser" %}
{% set version = "0.2.0" %}
{% set sha256 = "cc8142a424bcbcf8f7fe873418ae44502953bcf3507cd7e4582c7229d2740af2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -v"

requirements:
  host:
    - pip
    - python
    - six

  run:
    - matplotlib
    - python
    - six

test:
  imports:
    - databroker_browser

about:
  home: https://github.com/NSLS-II/databroker-browser
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A read-only dottable dictionary
