{% set version = "0.2.0" %}

package:
  name: databroker-browser
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/databroker-browser/archive/v{{ version }}.tar.gz
  fn: databroker-browser-v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - six

  run:
    - matplotlib
    - python
    - six

test:
  imports:
    - databroker_browser

about:
  home: https://github.com/NSLS-II/databroker-browser
  license: BSD 3-Clause
  summary: A read-only dottable dictionary
